---
- name: Install and Configure K3s on AlmaLinux
  hosts: k3s_cluster
  become: true  
  tasks:
    - name: Check curl is installed
      yum:
        name: curl
        state: present

    - name: Download and Install K3s
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Ensure K3s service is enabled and started
      systemd:
        name: k3s
        enabled: yes
        state: started
 
    - name: Ensure .kube directory exists
      file:
        path: /home/ikritik/.kube
        state: directory
        owner: ikritik
        group: ikritik
        mode: '0755'  

    - name: Copy kubeconfig file
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/ikritik/.kube/config
        owner: ikritik
        group: ikritik
        mode: '0600'
        remote_src: yes
    
    # - name: Export KUBECONFIG variable
    #   ansible.builtin.shell: |
    #     echo 'KUBECONFIG=$HOME/.kube/config' >> /home/ikritik/.bashrc
    #     source ~/.bashrc
    #   args:
    #     executable: /bin/bash
    #   become: false

    # - name: Add KUBECONFIG variable to .bashrc
    #   lineinfile:
    #     path: ~/.bashrc
    #     line: "export KUBECONFIG=$HOME/.kube/config"
    #     create: yes

    # - name: Apply changes by sourcing .bashrc
    #   shell: source ~/.bashrc
    #   args:
    #     executable: /bin/bash

    - name: Ensure /usr/local/bin is in PATH
      lineinfile:
        path: ~/.bashrc
        line: 'export PATH=$PATH:/usr/local/bin'
        create: yes

    - name: Test kubectl with shell
      ansible.builtin.shell: |
        export KUBECONFIG=$HOME/.kube/config
        kubectl get pods -A
      environment:
        KUBECONFIG: "{{ ansible_env.HOME }}/.kube/config"
      register: kubectl_output

    - name: Display kubectl output
      ansible.builtin.debug:
        var: kubectl_output.stdout