---
- name: Install and Configure K3s on AlmaLinux
  hosts: k3s_cluster
  become: true  
  tasks:
    # - name: Check curl is installed
    #   yum:
    #     name: curl
    #     state: present

    # - name: Download and Install K3s
    #   shell: |
    #     curl -sfL https://get.k3s.io | sh -
    #   args:
    #     creates: /usr/local/bin/k3s

    # - name: Ensure K3s service is enabled and started
    #   systemd:
    #     name: k3s
    #     enabled: yes
    #     state: started
 
    - name: Ensure .kube directory exists
      file:
        path: /home/ikritik/.kube
        state: directory
        owner: ikritik
        group: ikritik
        mode: '0755'    
    - name: Copy kubeconfig file
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/ikritik/.kube/config
        owner: ikritik
        group: ikritik
        mode: '0600'
        remote_src: yes
 
    - name: Test kubectl
      ansible.builtin.command: kubectl get pods
      register: kubectl

    - name: Show Pods from Register
      ansible.builtin.debug:
        var: "{{ kubectl}}"